import type { Metadata } from "next";
import "./globals.css";
import BackgroundScene from "@/components/scenes/BackgroundScene";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BackgroundScene/>
        {children}
      </body>
    </html>
  );
}
